// ===== AFRICAN & NIGERIAN RECIPE DATABASE =====
const AFRICAN_RECIPES = [
    {
        idMeal: 'afr001',
        strMeal: 'Jollof Rice',
        strDrinkAlternate: null,
        strCategory: 'Rice',
        strArea: 'Nigerian',
        strInstructions: `Heat oil in a large pot. Sauté onions until soft. Add tomato paste and fry for 3-4 minutes. Pour in blended tomatoes and peppers, cook for 15-20 minutes until oil separates. Add curry powder, thyme, bay leaves, and seasoning. Pour in stock and bring to boil. Add washed rice, reduce heat, cover tightly. Cook for 30-35 minutes without stirring. Fluff with fork and serve.`,
        strMealThumb: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&q=80',
        strTags: 'Rice,Nigerian,Main,Party',
        strYoutube: 'https://www.youtube.com/watch?v=example',
        strIngredient1: 'Long grain rice',
        strIngredient2: 'Tomatoes',
        strIngredient3: 'Red bell peppers',
        strIngredient4: 'Scotch bonnet peppers',
        strIngredient5: 'Onions',
        strIngredient6: 'Tomato paste',
        strIngredient7: 'Vegetable oil',
        strIngredient8: 'Chicken stock',
        strIngredient9: 'Curry powder',
        strIngredient10: 'Thyme',
        strIngredient11: 'Bay leaves',
        strIngredient12: 'Seasoning cubes',
        strMeasure1: '3 cups',
        strMeasure2: '5 large',
        strMeasure3: '3',
        strMeasure4: '2',
        strMeasure5: '2 large',
        strMeasure6: '3 tbsp',
        strMeasure7: '½ cup',
        strMeasure8: '4 cups',
        strMeasure9: '2 tsp',
        strMeasure10: '1 tsp',
        strMeasure11: '2',
        strMeasure12: '2',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr002',
        strMeal: 'Egusi Soup',
        strCategory: 'Soup',
        strArea: 'Nigerian',
        strInstructions: `Season and cook meats until tender. Heat palm oil, add chopped onions. Mix ground egusi with water to form paste. Add to pot and fry 2-3 minutes. Gradually add meat stock, stirring to prevent lumps. Add cooked meats, stockfish, crayfish, and pepper. Cook for 10 minutes. Add chopped vegetables, cook 5 minutes. Serve with pounded yam or eba.`,
        strMealThumb: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
        strTags: 'Soup,Nigerian,Traditional',
        strYoutube: '',
        strIngredient1: 'Ground egusi',
        strIngredient2: 'Palm oil',
        strIngredient3: 'Assorted meat',
        strIngredient4: 'Stockfish',
        strIngredient5: 'Pumpkin leaves',
        strIngredient6: 'Spinach',
        strIngredient7: 'Onions',
        strIngredient8: 'Crayfish',
        strIngredient9: 'Scotch bonnet',
        strIngredient10: 'Seasoning cubes',
        strMeasure1: '2 cups',
        strMeasure2: '½ cup',
        strMeasure3: '1 lb',
        strMeasure4: '1 cup',
        strMeasure5: '3 cups',
        strMeasure6: '2 cups',
        strMeasure7: '1 large',
        strMeasure8: '3 tbsp',
        strMeasure9: '2',
        strMeasure10: '3',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr003',
        strMeal: 'Suya (Spicy Grilled Meat)',
        strCategory: 'Beef',
        strArea: 'Nigerian',
        strInstructions: `Grind roasted peanuts to fine powder. Mix with cayenne, ginger, garlic powder, onion powder, bouillon, and salt. Thread beef onto skewers. Brush with oil, coat with suya spice. Marinate 30 minutes to 4 hours. Grill over medium-high heat 6-8 minutes, turning occasionally. Sprinkle more spice halfway. Serve with sliced onions and tomatoes.`,
        strMealThumb: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
        strTags: 'Beef,Grilled,Street Food,Nigerian',
        strYoutube: '',
        strIngredient1: 'Beef sirloin',
        strIngredient2: 'Peanuts',
        strIngredient3: 'Cayenne pepper',
        strIngredient4: 'Ground ginger',
        strIngredient5: 'Garlic powder',
        strIngredient6: 'Onion powder',
        strIngredient7: 'Bouillon powder',
        strIngredient8: 'Vegetable oil',
        strIngredient9: 'Onions',
        strIngredient10: 'Tomatoes',
        strMeasure1: '2 lbs',
        strMeasure2: '1 cup',
        strMeasure3: '2 tbsp',
        strMeasure4: '1 tbsp',
        strMeasure5: '1 tbsp',
        strMeasure6: '1 tbsp',
        strMeasure7: '2 tsp',
        strMeasure8: '3 tbsp',
        strMeasure9: '2',
        strMeasure10: '2',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr004',
        strMeal: 'Moi Moi (Bean Pudding)',
        strCategory: 'Vegetarian',
        strArea: 'Nigerian',
        strInstructions: `Blend peeled beans, peppers, and onions with water until smooth. Pour into bowl, add oil, seasoning, crayfish, and salt. Mix well. Grease moi moi containers. Pour mixture ¾ full, add egg or corned beef pieces. Steam in pot with boiling water for 45-60 minutes until firm. Cool slightly before unmolding.`,
        strMealThumb: 'https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=800&q=80',
        strTags: 'Beans,Steamed,Nigerian,Vegetarian',
        strYoutube: '',
        strIngredient1: 'Black-eyed beans',
        strIngredient2: 'Red bell peppers',
        strIngredient3: 'Scotch bonnet',
        strIngredient4: 'Onions',
        strIngredient5: 'Vegetable oil',
        strIngredient6: 'Seasoning cubes',
        strIngredient7: 'Crayfish',
        strIngredient8: 'Hard-boiled eggs',
        strIngredient9: 'Corned beef',
        strMeasure1: '3 cups',
        strMeasure2: '2',
        strMeasure3: '1',
        strMeasure4: '1 large',
        strMeasure5: '½ cup',
        strMeasure6: '3',
        strMeasure7: '2 tbsp',
        strMeasure8: '4',
        strMeasure9: '½ cup',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr005',
        strMeal: 'Pepper Soup',
        strCategory: 'Soup',
        strArea: 'Nigerian',
        strInstructions: `Season meat with salt, seasoning, and onions. Let marinate 15 minutes. Place in pot with water, cook until tender (30-40 min). Add pepper soup spice, scotch bonnet, uziza, ehuru. Simmer 10 minutes. Add remaining onions and scent leaves. Cook 2 minutes. Serve hot.`,
        strMealThumb: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
        strTags: 'Soup,Spicy,Nigerian',
        strYoutube: '',
        strIngredient1: 'Goat meat',
        strIngredient2: 'Pepper soup spice',
        strIngredient3: 'Scotch bonnet',
        strIngredient4: 'Onions',
        strIngredient5: 'Uziza seeds',
        strIngredient6: 'Ehuru',
        strIngredient7: 'Seasoning cubes',
        strIngredient8: 'Scent leaves',
        strMeasure1: '2 lbs',
        strMeasure2: '3 tbsp',
        strMeasure3: '2',
        strMeasure4: '1 medium',
        strMeasure5: '1 tsp',
        strMeasure6: '3 seeds',
        strMeasure7: '2',
        strMeasure8: '¼ cup',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr006',
        strMeal: 'Pounded Yam',
        strCategory: 'Side',
        strArea: 'Nigerian',
        strInstructions: `Peel and cut yam into chunks. Place in pot, cover with water, add salt. Boil 25-30 minutes until very soft. Drain, reserve some water. Pound with mortar and pestle or use stand mixer until smooth and stretchy. Add reserved water if too thick. Shape into balls, serve immediately with soup.`,
        strMealThumb: 'https://images.unsplash.com/photo-1585238341710-3ef1e4c2e3e3?w=800&q=80',
        strTags: 'Yam,Side,Nigerian,Traditional',
        strYoutube: '',
        strIngredient1: 'White yam',
        strIngredient2: 'Water',
        strIngredient3: 'Salt',
        strMeasure1: '3 lbs',
        strMeasure2: 'for boiling',
        strMeasure3: '½ tsp',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr007',
        strMeal: 'Waakye (Rice and Beans)',
        strCategory: 'Rice',
        strArea: 'Ghanaian',
        strInstructions: `Boil sorghum leaves in water 15 minutes. Strain, reserve purple liquid. Cook black-eyed peas with baking soda until almost tender (30 min). Add rice, reserved leaf liquid, salt. Add more water if needed. Cook until rice tender and water absorbed (20 min). Serve with shito, gari, fried fish, boiled eggs.`,
        strMealThumb: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?w=800&q=80',
        strTags: 'Rice,Beans,Ghanaian,African',
        strYoutube: '',
        strIngredient1: 'Rice',
        strIngredient2: 'Black-eyed peas',
        strIngredient3: 'Sorghum leaves',
        strIngredient4: 'Baking soda',
        strIngredient5: 'Salt',
        strMeasure1: '2 cups',
        strMeasure2: '1 cup',
        strMeasure3: '10',
        strMeasure4: '½ tsp',
        strMeasure5: 'to taste',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr008',
        strMeal: 'Thieboudienne',
        strCategory: 'Seafood',
        strArea: 'Senegalese',
        strInstructions: `Stuff fish with parsley, garlic, pepper mixture. Marinate 30 min. Fry fish in oil until golden. Set aside. In same pot, sauté onions, add tomato paste, cook 5 min. Add vegetables and stock. Simmer 30 min until tender. Remove vegetables. Add rice to cooking liquid, cook until done. Serve rice on platter with fish and vegetables on top.`,
        strMealThumb: 'https://images.unsplash.com/photo-1633436059998-15cdccb02197?w=800&q=80',
        strTags: 'Fish,Rice,Senegalese,African',
        strYoutube: '',
        strIngredient1: 'Whole fish',
        strIngredient2: 'Broken rice',
        strIngredient3: 'Tomato paste',
        strIngredient4: 'Carrots',
        strIngredient5: 'Cabbage',
        strIngredient6: 'Eggplant',
        strIngredient7: 'Cassava',
        strIngredient8: 'Habanero',
        strIngredient9: 'Onions',
        strIngredient10: 'Garlic',
        strIngredient11: 'Parsley',
        strIngredient12: 'Oil',
        strMeasure1: '2 lbs',
        strMeasure2: '3 cups',
        strMeasure3: '4 tbsp',
        strMeasure4: '3',
        strMeasure5: '½ head',
        strMeasure6: '1',
        strMeasure7: '1 lb',
        strMeasure8: '2',
        strMeasure9: '2',
        strMeasure10: '4 cloves',
        strMeasure11: '¼ cup',
        strMeasure12: '½ cup',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr009',
        strMeal: 'Akara (Bean Fritters)',
        strCategory: 'Snack',
        strArea: 'Nigerian',
        strInstructions: `Soak beans overnight, peel skins. Blend with onions, peppers, and little water to thick paste. Add salt, seasoning. Beat mixture until fluffy. Heat oil to 350°F. Drop spoonfuls into hot oil. Fry until golden brown, 3-4 minutes. Drain on paper towels. Serve hot with pap or bread.`,
        strMealThumb: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&q=80',
        strTags: 'Beans,Fried,Snack,Nigerian',
        strYoutube: '',
        strIngredient1: 'Black-eyed beans',
        strIngredient2: 'Onions',
        strIngredient3: 'Scotch bonnet',
        strIngredient4: 'Salt',
        strIngredient5: 'Seasoning',
        strIngredient6: 'Vegetable oil',
        strMeasure1: '2 cups',
        strMeasure2: '1 medium',
        strMeasure3: '1',
        strMeasure4: 'to taste',
        strMeasure5: '1 tsp',
        strMeasure6: 'for frying',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    },
    {
        idMeal: 'afr010',
        strMeal: 'Chin Chin',
        strCategory: 'Dessert',
        strArea: 'Nigerian',
        strInstructions: `Mix flour, sugar, baking powder, nutmeg. Rub in butter until crumbly. Add milk gradually to form dough. Knead until smooth. Roll out thin, cut into small squares. Heat oil to 350°F. Fry chin chin until golden brown. Drain on paper towels. Cool completely before storing.`,
        strMealThumb: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800&q=80',
        strTags: 'Snack,Fried,Nigerian,Dessert',
        strYoutube: '',
        strIngredient1: 'All-purpose flour',
        strIngredient2: 'Sugar',
        strIngredient3: 'Butter',
        strIngredient4: 'Milk',
        strIngredient5: 'Baking powder',
        strIngredient6: 'Nutmeg',
        strIngredient7: 'Vegetable oil',
        strMeasure1: '4 cups',
        strMeasure2: '½ cup',
        strMeasure3: '½ cup',
        strMeasure4: '½ cup',
        strMeasure5: '1 tsp',
        strMeasure6: '½ tsp',
        strMeasure7: 'for frying',
        strSource: '',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
    }
];

// Export for use in main app
if (typeof module !== 'undefined' && module.exports) {
    module.exports = AFRICAN_RECIPES;
}
